# ##################################
# MOES SS01 3-Way Light Switch
# ##################################
# D2 GPIO04: white led (inverted)
# D1 GPIO05: red led (inverted)
# D6 GPIO12: relay
# D7 GPIO13: button (inverted)
# D5 GPIO14: power/usage sensor (inverted)
# ##################################


substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: basement_stair_lights
  friendly_name: Basement Stair Lights
  ip_address: !secret basement_stair_lights_ip
  icon: "mdi:lightbulb"


esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1


# web_server:
#   port: 80
  # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


status_led:
  # https://esphome.io/components/status_led
  pin:
    number: GPIO5   # Red LED
    inverted: True


binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO14
      inverted: True
    id: sensor
    name: ${friendly_name} Sensor
    filters:
      - delayed_off: 50ms
    on_press:
      - switch.turn_off: white_led
    on_release:
      - switch.turn_on: white_led
    internal: True

  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO13
      inverted: True
    id: button
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
    internal: True


switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    id: white_led
    name: ${friendly_name} White LED
    pin:
      number: GPIO4
      inverted: True
    restore_mode: RESTORE_DEFAULT_ON
    internal: True

  - platform: gpio
    pin: GPIO12
    id: relay
    name: ${friendly_name} Relay
    internal: True

  # present the state of the switch in HA based on the sensor
  - platform: template
    # https://esphome.io/components/switch/template.html
    name: ${friendly_name}
    id: ${device_name}
    icon: ${icon}
    lambda: |-
      if (id(sensor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.toggle: relay
    turn_off_action:
      - switch.toggle: relay
